[package]
name = "nuhxboard"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "NuhxBoard"
path = "src/main.rs"

[dependencies]
async-std = "1.12.0"
clap = { version = "4.4.18", features = ["derive"] }
colorgrad = "0.6.2"
futures = "0.3.30"
home = "0.5.9"
iced = { version = "0.10.0", features = [
  "image",
  "canvas",
  "advanced",
  "async-std",
] }
image = { version = "0.24.8", features = ["ico"] }
regex = "1.10.2"
serde = { version = "1.0.195", features = ["serde_derive"] }
serde_json = "1.0.111"
