[package]
name = "nuhxboard"
version = "0.1.4"
edition = "2021"
license = "GPL-3.0"
authors = ["Devin Droddy <devin.droddy@gmail.com>"]
description = "A Linux port of NohBoard"
repository = "https://github.com/ThePyroTF2/NuhxBoard"
keywords = ["keyboard", "virtual", "overlay", "linux", "nohboard"]
categories = ["visualization"]
readme = "README.md"
rust-version = "1.72.0"
include = ["src/**/*", "Cargo.toml", "LICENSE", "README.md", "NuhxBoard.png"]

[dependencies]
async-std = "1.12.0"
clap = { version = "4.4.18", features = ["derive"] }
color-eyre = { version = "0.6.2", default-features = false }
colorgrad = "0.6.2"
futures = "0.3.30"
home = "0.5.9"
iced = { version = "0.10.0", features = [
  "image",
  "canvas",
  "advanced",
  "async-std",
] }
image = { version = "0.24.8", features = ["ico"] }
inquire = "0.6.2"
rdev = "0.5.3"
serde = { version = "1.0.195", features = ["serde_derive"] }
serde_json = "1.0.111"

# The profile that 'cargo dist' will build with
[profile.dist]
inherits = "release"
lto = "thin"

# Config for 'cargo dist'
[workspace.metadata.dist]
# The preferred cargo-dist version to use in CI (Cargo.toml SemVer syntax)
cargo-dist-version = "0.8.2"
# CI backends to support
ci = ["github"]
# The installers to generate for each app
installers = []
# Target platforms to build apps for (Rust target-triple syntax)
targets = ["x86_64-unknown-linux-gnu"]
# Publish jobs to run in CI
pr-run-mode = "plan"
