[package]
name = "nuhxboard"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.4.18", features = ["derive"] }
colors-transform = "0.2.11"
futures = "0.3.30"
iced = { version = "0.10.0", features = ["image", "canvas", "advanced"] }
regex = "1.10.2"
serde = { version = "1.0.195", features = ["serde_derive"] }
serde_json = "1.0.111"
