[package]
name = "kbdisplay"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
iced = { version = "0.10.0", features = ["image"] }
regex = "1.10.2"
serde = { version = "1.0.195", features = ["serde_derive"] }
serde_json = "1.0.111"
