name: Build
on:
  push:
    branches: ["main"]
    paths:
      - '**.rs'
  pull_request:
    branches: ["main"]
env:
  CARGO_TERM_COLOR: always
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: awalsh128/cache-apt-pkgs-action@v1.3.1
        with:
          packages: libx11-dev
          version: 1.0
      - name: Build
        run: cargo build --verbose
      - name: Run tests
        run: cargo test --verbose
